### ISSUE TITLE
Fails on npm run build

### ISSUE THREAD

**Issue by jjstrat3** [JSBros/hedron#44]
First off, great library @garetmckinley !

I just pulled down your library locally to do some hacking on it for the purpose of possibly contributing on some of the outstanding open issues.  It failed on executing `npm run build` on my machine.

Here's my steps after cloning your repo:

1. `yarn install`
2. `npm run build`

I get this output in my terminal:

```bash
> hedron@0.4.0 build /Users/jstratton/Documents/workspace/hedron
> npm run build:lib && npm run build:dist


> hedron@0.4.0 build:lib /Users/jstratton/Documents/workspace/hedron
> babel src --out-dir lib

node_modules/nan
resolve failed:  { Error: Cannot find module 'eslint-module-utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } eslint-module-utils
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } babel-runtime
src/components/Column.js -> lib/components/Column.js
src/components/Page.js -> lib/components/Page.js
src/components/Row.js -> lib/components/Row.js
src/index.js -> lib/index.js
src/utils/divvy.js -> lib/utils/divvy.js
src/utils/index.js -> lib/utils/index.js
src/utils/media.js -> lib/utils/media.js
src/utils/passOn.js -> lib/utils/passOn.js

> hedron@0.4.0 build:dist /Users/jstratton/Documents/workspace/hedron
> rollup -c && rollup -c --environment PRODUCTION

Creating development bundle...
node_modules/nan
resolve failed:  { Error: Cannot find module 'eslint-module-utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } eslint-module-utils
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } babel-runtime
Creating production bundle...
node_modules/nan
resolve failed:  { Error: Cannot find module 'eslint-module-utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } eslint-module-utils
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/jstratton/Documents/workspace/hedron/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/jstratton/Documents/workspace/hedron/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } babel-runtime
```

Possibly an upstream dependency of babel rollup preset??

**Comment by garetmckinley** [comment]
Hello, thanks for the kind words! Sorry you're having those issues though, do you have either `eslint` or `babel` installed at a global scope? I'm going to test out a fresh clone of this repo on my other computer in the hopes I can duplicate the issue.

**Comment by jjstrat3** [comment]
@garetmckinley Np.  Don't have `eslint` or `babel` installed globally, just the `eslint-cli` npm module...which hasn't caused issues for me before with my own projects, but who knows. ;)
If it's relevant, I'm using `6.9.1` of `node` via `nvm`.

**Comment by garetmckinley** [comment]
OK, so I found a few interesting things!

On a fresh clone of the repo, I get identical output to you. However, my package is still compiled in the `dist/` subdir. Can you check and see if the same is true for you?

I can't seep to supress the `eslint-module-utils` error though, even after I run `npm install --save-dev eslint-module-utils`. I'm running node `v7.0.0`.

**Comment by mikkom** [comment]
@garetmckinley I guess this can be closed now as well since #45 has been merged?

**Comment by jjstrat3** [comment]
@mikkom @garetmckinley haven't had a chance to test it yet again, but I'll pull latest as soon as I get to the office in the next hour

**Comment by jjstrat3** [comment]
@mikkom @garetmckinley pulled latest from `master`, and everything seems to build fine.  I'll go ahead and close this.  Thanks!

**Comment by garetmckinley** [comment]
Awesome, glad to hear @jjstrat3 👍
